import { Book } from '@/features/book/models/book.model';

export const mockBooks: Book[] = [
  {
    id: 1,
    title: '1984',
    author: 'George Orwell',
    status: 'free',
    description: '',
    ownerId: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
    availableAt: new Date(),
    available: true,
  },
  {
    id: 2,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    status: 'checked out',
    description: '',
    ownerId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    availableAt: new Date('2025-09-04T00:00:00Z'),
    available: false,
  },
  {
    id: 3,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    status: 'reserved',
    description: '',
    ownerId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    availableAt: new Date('2025-09-05T00:00:00Z'),
    available: false,
  },
];
